#!/bin/bash

# Auto suspend and wake-up script
#
# Puts the computer on standby and automatically wakes it up at specified time
#
# Inspired from Romke van der Meulen <redge.online@gmail.com>
# Modified by Jack Xu <jxdock@gmail.com>
# Takes a 24hour time HH:MM as its argument
# Example:
# suspend_until 9:30
# suspend_until 18:45

# ------------------------------------------------------
# Argument check
if [ $# -lt 1 ]; then
    echo "Usage: suspend_until HH:MM"
    exit
fi

# Check whether specified time today or tomorrow
DESIRED=$((`date +%s -d "$1"`))
NOW=$((`date +%s`))
if [ $DESIRED -lt $NOW ]; then
    DESIRED=$((`date +%s -d "$1"` + 24*60*60))
fi

# Set RTC wakeup time
echo "clear wake alarm"
sh -c "echo 0 > /sys/class/rtc/rtc0/wakealarm" 

echo "scheduling wake time @ $1 with $DESIRED ..."
sh -c "echo $DESIRED > /sys/class/rtc/rtc0/wakealarm"

# feedback
echo "Scheduled, goodbye ..."

# give rtcwake some time to make its stuff
sleep 2
echo "Now proceed shutdown!"
